server:
    port: 8081

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true

spring:
    application:
        name: user-service
    datasource:
        url: dbc:postgresql://localhost:5432/ocp_user_db
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: Duster@12345
        #Duster@12345 or root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect


